import { Inter } from 'next/font/google';

import Header from '@/components/Header';
import Sidebar from '@/components/Sidebar';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="flex">
          <Sidebar />
          <div className="flex-1 sm:ml-20 md:ml-56">{children}</div>
        </div>
      </body>
    </html>
  );
}
